version: "3.8"
services:
  go:
    build: .
    environment: 
      - POSTGRES_HOST=postgres
    depends_on: 
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: postgres 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      #- POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    user: root 
    volumes:
      - ./testdata/postgres/init:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/pgdata
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  pg-data:
    driver: local