version: "3.8"
services:
  postgresql:
    image: postgres
    container_name: postgres 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      #- POSTGRES_DB=postgres
    
    ports:
      - "5432:5432"
    user: root 
    volumes:
      - ./testdata/postgres/init:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/pgdata
volumes:
  pg-data:
    driver: local