name: Test

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: docker compose -f docker-compose-test.yml up --build --exit-code-from go
